data:
  type: paraphrase # translate/paraphrase
  path: data/paraphrase
#  source_col: src_text
#  target_col: dst_text
  source_col: original
  target_col: ru

data_train: data/processed/train
data_test: data/processed/test

model:
  type: "qwen" # mt5 or qwen
#  path: models/mt5-small/
  path: models/qwen/
  device: "cuda:0"

shift:
  type: None # None/length/clusters
  path: data/processed/clusters


new_model_path: models/model/
model_save_path: "/userspace/bma/BIRMTranslation/model_checkpoints"

train_params:
  test_dataset_size: 1000
  num_epochs: 2
  batch_size: 2
  learning_rate: 1e-3
  gamma: 0.999996
  device: 'cuda'
  kommulation_steps: 2
  eval_every_step: 1000
